# APACHE
#
# VERSION	0.1

FROM ucodev/base

MAINTAINER Pedro A. Hortas <pah@ucodev.org>
LABEL Description="Installs the Apache HTTP Server" Vendor="uCodev" Version="0.1"

# Inform about the used ports
EXPOSE 80

# Install Apache2 and PHP
RUN apt-get install -y apache2 php libapache2-mod-php

